package com.singulee.carschool.pojo;

import java.sql.Date;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.carId
     *
     * @mbg.generated
     */
    private Integer carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.carNumber
     *
     * @mbg.generated
     */
    private String carnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.carDriverClass
     *
     * @mbg.generated
     */
    private Integer cardriverclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.staute
     *
     * @mbg.generated
     */
    private String staute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cartStartDate
     *
     * @mbg.generated
     */
    private Date cartstartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.carEndDate
     *
     * @mbg.generated
     */
    private Date carenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.extend2
     *
     * @mbg.generated
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.carId
     *
     * @return the value of cart.carId
     *
     * @mbg.generated
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.carId
     *
     * @param carid the value for cart.carId
     *
     * @mbg.generated
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.carNumber
     *
     * @return the value of cart.carNumber
     *
     * @mbg.generated
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.carNumber
     *
     * @param carnumber the value for cart.carNumber
     *
     * @mbg.generated
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.carDriverClass
     *
     * @return the value of cart.carDriverClass
     *
     * @mbg.generated
     */
    public Integer getCardriverclass() {
        return cardriverclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.carDriverClass
     *
     * @param cardriverclass the value for cart.carDriverClass
     *
     * @mbg.generated
     */
    public void setCardriverclass(Integer cardriverclass) {
        this.cardriverclass = cardriverclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.staute
     *
     * @return the value of cart.staute
     *
     * @mbg.generated
     */
    public String getStaute() {
        return staute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.staute
     *
     * @param staute the value for cart.staute
     *
     * @mbg.generated
     */
    public void setStaute(String staute) {
        this.staute = staute == null ? null : staute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.cartStartDate
     *
     * @return the value of cart.cartStartDate
     *
     * @mbg.generated
     */
    public Date getCartstartdate() {
        return cartstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.cartStartDate
     *
     * @param cartstartdate the value for cart.cartStartDate
     *
     * @mbg.generated
     */
    public void setCartstartdate(Date cartstartdate) {
        this.cartstartdate = cartstartdate ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.carEndDate
     *
     * @return the value of cart.carEndDate
     *
     * @mbg.generated
     */
    public Date getCarenddate() {
        return carenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.carEndDate
     *
     * @param carenddate the value for cart.carEndDate
     *
     * @mbg.generated
     */
    public void setCarenddate(Date carenddate) {
        this.carenddate = carenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.extend2
     *
     * @return the value of cart.extend2
     *
     * @mbg.generated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.extend2
     *
     * @param extend2 the value for cart.extend2
     *
     * @mbg.generated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}